services:
  - type: web
    name: app-recouvrement
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
